### ISSUE TITLE
Gap analysis agains NISO STS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-standoc#3]
Looks like they only have a PDF format. Not sure how this actually facilitates information exchange...

https://groups.niso.org/apps/group_public/download.php/18492/Z39.102-2017.pdf

Point is we need to handle gaps, if any.

**Comment by TAC-NISO** [comment]
I'm not sure how you seem to have missed this, but there is an entire site of information on the NISO STS standard and its various outputs.  http://www.niso-sts.org/
The STS standard is available in a variety of serializations on this page: http://www.niso-sts.org/DTDs-XSDs-RNGs.html

" user convenience, both of the NISO STS tag sets (Interchange and Extended) are provided in DTD, XSD, and RNG formats. And, in all of these formats, each schema is provided with MathML2 and MathML3 versions. The models represented by the DTD, XSD, and RNG forms are logically identical, and interchange is unaffected by the form chosen. Users are encouraged to use the form of constraint language that works best with their chosen tools."

NISO did publish a normative PDF version of the standard, but for obvious reasons this is certainly not the most useful version, nor was it intended to be applied as such.  

I might also note that the URL for this project is pitching a 404: https://www.metanorma.com

**Comment by ronaldtse** [comment]
@TAC-NISO thank you for the comment and links, they are very helpful indeed. 

In the framework, STS can be considered as an output format of Metanorma (e.g., IETF RFC XML). The goal of this ticket is to find out any gaps between the Metanorma model and STS so we can support creation of STS output.

We apologize for the 404 since we are just starting to produce the website 😉 

cc: @ribose-jeffreylau @opoudjis

**Comment by ronaldtse** [comment]
More clarification. The Metanorma StandardDocument model is not a _rendering markup language_. It is a standalone, semantic document model that can be adopted by standard bodies via instantiation.

The semantic approach is being used to drive different rendering of a range of standards on different platforms. For example, Metanorma retains the normative or informative nature of every clause and subclause, as well as for cross-references. Display choices such as list bullets styles and dimensions are rendering concerns and thus are only specified in the output formats.

Since documents in StandardDocument (and its instances) retain full semantics, they can be:

* directly rendered into final output formats such as HTML and Word, and
* used to produce output formats that are intermediate (i.e., not intended for human consumption), for example, the IETF RFC XML and NISO STS.

This allows the content author to maintain all semantic content, while leaving out all stylistic and rendering concerns.
