### ISSUE TITLE
SIM compare: missing connection to the MRR and OGC ModSpec models?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-standoc#40]
Where in the models do they connect?

**Comment by opoudjis** [comment]
Right now, they don't. Oops.

The intention was to invoke the  models in metanorma-requirements-models as some sort of plug-in grammar, although we haven't implemented that in the Relax grammar. I'll go ahead and do an external invocation now.

**Comment by opoudjis** [comment]
I'm going to just use the generic term Provision, and invoke metanorma-requirements-models as its source.

**Comment by ronaldtse** [comment]
@opoudjis In the last meeting with Christian of SG 12 TF 3 we reviewed the requirement models and perhaps we should find a way to better align MRR with ModSpec, because it's more reasonable that way. MRR today doesn't differentiate Requirements and Tests well and also doesn't really have collections (it uses sub-requirements instead).

**Comment by opoudjis** [comment]
... Well, given that we are not using any model  apart from ModSpec at all, and the existing code works, and our users are not studying the XML, I think that is not a good use of my time. 

No refactoring until we have a real alternate requirements model, that someone cares about using. And we haven't implemented one in five years.

I mean, yes, I could introduce a distinct requirement-test object, or even a requirement-collection object (spoiler alert for the latter: over either my dead body—or someone else's, it's a distinction without a difference that will just mess the code up.) But this is cosmetic stuff, and we continue to have more important things to do.

**Comment by opoudjis** [comment]
This ticket, at any rate, is closing. If you want to propose reengineering the requirements model, it needs to be a distinct ticket, with concrete requirements.
