### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [metanorma/metanorma-model-standoc#5]
Convert metanorma standard document StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse,  please find the zip archives that include the results of conversion.

- [PNG.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2317167/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2317168/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2317169/SVG.zip)

**Comment by VasBu** [comment]
@ronaldtse, Bibliography diagram has been updated (+ prefix has been removed from an enumeration type)

- [PNG-StandardDoc_Bibliography.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2338885/PNG-StandardDoc_Bibliography.zip)
- [SOURCE-StandardDoc_Bibliography.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2338886/SOURCE-StandardDoc_Bibliography.zip)
- [SVG-StandardDoc_Bibliography.zip](https://github.com/riboseinc/metanorma-model-standoc/files/2338887/SVG-StandardDoc_Bibliography.zip)

**Comment by ronaldtse** [comment]
This is all done. Thanks @VasBu !
