### ISSUE TITLE
Allow adding "LICENSE" to document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-standoc#7]
Copyright statements, licenses, patent statements.

It may be beneficial to have them contained in the model.

**Comment by opoudjis** [comment]
I would like to make this a vague "boilerplate" container, which can contain more specific tags in particular models, such as "authority" in NIST.

**Comment by opoudjis** [comment]
Regarding https://github.com/metanorma/metanorma-model-standoc/issues/7#issuecomment-478767474 can you help check nutcracker model? Just don’t want to miss anything. Thanks!

**Comment by ronaldtse** [comment]
@opoudjis when you have time please help check the nutcracker model on this issue. Thanks!

**Comment by opoudjis** [comment]
Said standard has a "permissions" within the topmost document metadata element, which incorporates copyright information and license information. The NIST authority statement is neither: it refers to the legal framework of the standards, and to the period during which comments can be solicited.

So we have four elements at minimum, and there may well be more:

* Copyright statement
* License statement
* Legal statement
* Feedback statement (which is not quite like the others)

I can create a distinct generic container for each at Metanorma level, I guess, but different standards may well have more. The container for these should still be `<boilerplate>`, they are distinct from the document preface.

**Comment by opoudjis** [comment]
This modelling choice will force me to refactor the `authority` markup in NIST, chopping it up into less arbitrary bits. (There is still arbitrariness in the format changes.)
